openapi: "3.0.3"
info:
  title: "ale_arsenal API"
  description: "ale_arsenal API"
  version: "1.0.0"
servers:
- url: "https://ale_arsenal"
paths:
  /api/ingredient:
    get:
      description: ""
      responses:
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/IngredientDto"
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/NewIngredientCommand"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/NewIngredientDto"
  /api/ownBeer:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/NewOwnBeerCommand"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/NewOwnBeerDto"
components:
  schemas:
    IngredientDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        amount:
          type: "number"
          format: "double"
        ingredientType:
          type: "string"
      required:
      - "name"
      - "ingredientType"
    NewIngredientCommand:
      type: "object"
      properties:
        name:
          type: "string"
        amount:
          type: "number"
          format: "double"
        ingredientType:
          type: "string"
      required:
      - "name"
      - "ingredientType"
    NewIngredientDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
    NewOwnBeerCommand:
      type: "object"
      properties:
        name:
          type: "string"
        bottleSize:
          type: "number"
          format: "double"
        kegSize:
          type: "number"
          format: "double"
        bottleAmount:
          type: "integer"
          format: "int32"
        kegAmount:
          type: "integer"
          format: "int32"
        abv:
          type: "number"
          format: "double"
        style:
          type: "string"
        brewDate:
          type: "string"
        description:
          type: "string"
      required:
      - "name"
      - "style"
      - "brewDate"
      - "description"
    NewOwnBeerDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"