name: Build Backend

on:
  push:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'ale-arsenal-backend'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Start db container
        run: docker compose up --build db -d
      - name: Run build
        run: ./gradlew build